### ISSUE TITLE
Using the Python API returning incomplete location object

### ISSUE THREAD

**Issue by Carpintonto** [mdredze/carmen-python#2]
Trying to resolve tweets "on the fly" from the twitter stream API :

def get_location(data):
    location = resolver.resolve_tweet(data)
    return location

getting results typical:

(False, Location(country='United States', known=True, id=2645))
(False, Location(country='United States', state='California', known=True, id=440))
(False, Location(country='United States', state='New York', county='Erie County', city='Buffalo', known=True, id=2583))
(False, Location(country='United States', state='Tennessee', county='Robertson County', city='Springfield', known=True, id=3243))
(False, Location(country='United States', state='North Carolina', county='Davidson County', city='Thomasville', known=True, id=4604))
(False, Location(country='United States', state='Michigan', known=True, id=3046))
(False, Location(country='United States', state='Florida', known=True, id=3033))
(False, Location(country='United States', state='District of Columbia', county='District of Columbia', city='Washington', known=True, id=2575))
(False, Location(country='United States', state='District of Columbia', known=True, id=3032))

How do I call to include latitude, longitude, and resolution_method?

The frontend returns everything.  This is a great program.  Thank you!

**Comment by query** [comment]
The default `repr` of `Location` doesn't include `latitude`, `longitude`, or `resolution_method`, but those fields are on the actual object, and can be fetched with e.g. `location.latitude`.

Please reopen this issue if the fields appear to actually be missing from the object. Thanks!

**Comment by Carpintonto** [comment]
thanks Roger -

that is the clue I needed:
https://docs.python.org/3.6/reference/datamodel.html#object.__repr__
