### ISSUE TITLE
Compatibility with twitter api 2

### ISSUE THREAD

**Issue by manisci** [mdredze/carmen-python#9]
Hi,

Thank you for this useful library. I modified the code a little bit to make it work with twitter api version 2. I have tested this on some Tweets I have acquired from the academic research endpoint using 'twarc2' library and it works on them. I used the following pages to change the code. 

[](url)https://visual-data-format-migration-tool.glitch.me/
[](url)https://developer.twitter.com/en/docs/twitter-api/migrate/data-formats

I have created a fork and committed the changes there. I thought I put it here in case someone may find it useful. 

[](url)https://github.com/manisci/carmen-python_api2

Thank you,
Mani Sotoodeh

**Comment by AADeLucia** [comment]
@jackjyzhang how do these updates compare with the ones in your branch?

@manisci Thank you, we have been working on updating the API compatibility as well but I don't think the changes are in the main branch yet.

**Comment by AADeLucia** [comment]
Updated with Carmen 2.0
